tmf: Add a more reliable way to get the active editor with SWTBot
StandardImportGzipTraceTest assumes that after double-clicking on the
trace, there will be an active editor right away. Instead, we can
have a method that waits until there is an active editor.

I've seen the failure:
WidgetNotFoundException: There is no active editor
here:
http://eclip.se/5l

Change-Id: I41dd5c7c4f30f789dabab813eb8bcbb81fdcb48e
Signed-off-by: Marc-Andre Laperle <marc-andre.laperle@ericsson.com>
Reviewed-on: https://git.eclipse.org/r/54154
Reviewed-by: Hudson CI
Reviewed-by: Patrick Tasse <patrick.tasse@gmail.com>